export const SEARCH_LOGIN_SAGA = 'SEARCH_LOGIN_SAGA';

export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_USERS_LIST = 'FETCH_USERS_LIST';
export const FETCH_USERS_LIST_SAGA = 'FETCH_USERS_LIST_SAGA';
export const USERS_LIST_OPENED_FLAG = 'USERS_LIST_OPENED_FLAG';

export const CARD_OPEN_FLAG = 'CARD_OPEN_FLAG';

export const LOADING = 'LOADING';

export const ERROR = 'ERROR';
