export const SEARCH_LOGIN_SAGA = 'SEARCH_LOGIN_SAGA';
export const SEARCH_INIT_SAGA = 'SEARCH_INIT_SAGA';

export const FETCH_ALL_HISTORY = 'FETCH_ALL_HISTORY';
export const FETCH_SEARCH_HISTORY = 'FETCH_SEARCH_HISTORY';
export const SEARCH_HISTORY_LIST_FLAG = 'SEARCH_HISTORY_LIST_FLAG';
export const SEARCH_HISTORY_MODAL_FLAG = 'SEARCH_HISTORY_MODAL_FLAG';

export const GET_LOCAL_HISTORY_SAGA = 'GET_LOCAL_HISTORY_SAGA';

export const FETCH_LOGIN = 'FETCH_LOGIN';
export const FETCH_USERS_LIST = 'FETCH_USERS_LIST';
export const FETCH_USERS_LIST_SAGA = 'FETCH_USERS_LIST_SAGA';
export const USERS_LIST_OPENED_FLAG = 'USERS_LIST_OPENED_FLAG';

export const CARD_OPEN_FLAG = 'CARD_OPEN_FLAG';

export const LOADING = 'LOADING';

export const ERROR = 'ERROR';

export const REPOS_LIST_SAGA = 'REPOS_LIST_SAGA';
export const FETCH_REPOS_LIST = 'FETCH_REPOS_LIST';
export const REPOS_OPENED_LIST_FLAG = 'REPOS_OPENED_LIST_FLAG';

export const SEARCH_START = 'SEARCH_START';

export const SEARCH_IS_MOBILE = 'SEARCH_IS_MOBILE';
export const SEARCH_IS_MOBILE_START = 'SEARCH_IS_MOBILE_START';
