export const FAVORITE_BTN_FLAG = 'FAVORITE_BTN_FLAG';
export const FAVORITE_LIST_SAGA = 'FAVORITE_LIST_SAGA';
export const FAVORITE_LIST_FLAG = 'FAVORITE_LIST_FLAG';
export const FAVORITE_LIST_ADD = 'FAVORITE_LIST_ADD';
export const FAVORITE_LIST = 'FAVORITE_LIST';
export const FAVORITE_USER_FLAG = 'FAVORITE_USER_FLAG';

export const NOTE_FLAG = 'NOTE_FLAG';
