export const FAVORITE_BTN_FLAG = 'FAVORITE_BTN_FLAG';
export const FAVORITE_LIST_SAGA = 'FAVORITE_LIST_SAGA';
export const FAVORITE_LIST_ADD = 'FAVORITE_LIST_ADD';
export const FAVORITE_LIST = 'FAVORITE_LIST';
